# Generated by Django 5.2.15 on 2026-07-29 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=100, unique=True)),
                ('turkish_meaning', models.TextField()),
                ('turkish_meaning2', models.TextField(blank=True, default='')),
                ('turkish_meaning3', models.TextField(blank=True, default='')),
                ('level', models.CharField(blank=True, default='', max_length=5)),
                ('example', models.TextField(blank=True, default='')),
                ('definition', models.TextField(blank=True, default='')),
                ('phonetic', models.CharField(blank=True, default='', max_length=100)),
                ('audio_url', models.URLField(blank=True, default='')),
                ('known_count', models.IntegerField(default=0)),
                ('unknown_count', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_known', models.BooleanField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.word')),
            ],
        ),
    ]
