# Generated by Django 5.2.15 on 2026-08-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_levelprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100, unique=True)),
                ('meaning1', models.CharField(blank=True, max_length=255)),
                ('meaning2', models.CharField(blank=True, max_length=255)),
                ('meaning3', models.CharField(blank=True, max_length=255)),
                ('level', models.CharField(blank=True, max_length=10)),
                ('source', models.CharField(choices=[('csv', 'csv'), ('gemini', 'gemini'), ('api', 'api')], default='csv', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
