# Generated by Django 5.2.15 on 2026-08-03 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_wordbank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='levelprogress',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='word_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_words', to='api.wordbank'),
        ),
        migrations.AlterField(
            model_name='word',
            name='english_word',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('user', 'english_word'), name='unique_user_english_word'),
        ),
    ]
