# Generated by Django 5.2.15 on 2026-08-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_accountactiontoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountactiontoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
