# Generated by Django 5.2.15 on 2026-09-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_accountactiontoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbank',
            name='audio_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wordbank',
            name='definition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wordbank',
            name='dictionary_lookup_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wordbank',
            name='example',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wordbank',
            name='phonetic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
